environment:
  MEMCACHED_URL: 127.0.0.1:11211

# Do not insert any code under here without making sures it's in publishingtest first
os:
  - Visual Studio 2017

platform:
  - x64

services:
  - memcached

install:
  - choco install -y memcached
  - ps: Install-Product node 10
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/v4/scripts/connector/package-connector.sh
  - bash package.sh
  - For /d %%d in ( build\** ) do MOVE %%d %cd%

artifacts:
  - path: 'build\*.zip'
    name: 'deepstream.io-connector'

  - path: '**\*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token: ${GITHUB_TOKEN}
    artifact: 'deepstream.io-connector'
    draft: false
    on:
      appveyor_repo_tag: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/v4/scripts/connector/test-connector.sh
  - chmod 555 test.sh
  - bash test.sh

build: off
